version: '3.3'
services:
  backend:
    container_name: backend
    build: ./java/api-bdd/simple-api-main/simple-api
    networks:
      - app1-network
    ports:
      - 8080:8080
    depends_on:
      - database

  database:
    container_name: database
    build: ./postgres
    networks:
      - app1-network
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=usr
      - POSTGRES_PASSWORD=pwd
    volumes:
      - /devops/postgres/data:/var/lib/postgresql/data

  adminer:
    container_name: adminer
    image: adminer
    networks:
      - app1-network
    ports:
      - 8081:8080
    depends_on:
      - database

  httpd:
    container_name: httpd
    build: ./http
    ports:
      - 80:80
    networks:
      - app1-network
    depends_on:
      - backend

networks:
  app1-network: